import type { KbGroup } from "./documentationTypes";

export const knowledgebaseGroups: KbGroup[] = [
  {
    id: "account",
    title: "Account & businesses",
    description: "One login, multiple company workspaces, and invites.",
    articleIds: [
      "add-another-business",
      "switch-between-businesses",
      "join-business-by-invite",
    ],
  },
  {
    id: "getting-started",
    title: "Getting started",
    description: "First-time workspace setup and daily basics.",
    articleIds: [
      "start-90-day-trial",
      "setup-wizard",
      "process-policies-foundation",
      "attachment-requirements",
      "skip-setup-remind-later",
      "invited-during-setup",
      "onboarding-playbook",
      "load-slip-overview",
      "inventory-master-data",
      "user-management-admin",
      "form-field-settings",
      "tax-and-currency",
      "demo-data-training",
    ],
  },
  {
    id: "branches",
    title: "Branches & locations",
    description: "Set up warehouses or branches and choose which one you are working in.",
    articleIds: ["add-branch", "switch-active-branch"],
  },
  {
    id: "selling",
    title: "Selling",
    description: "Quotations, sales orders, sales invoices, and group invoicing.",
    articleIds: [
      "quotation-to-sales-flow",
      "sales-order-release",
      "sales-order-load-slip-quotation",
      "sales-load-slip-quotation",
      "sales-load-slip-so",
      "sales-load-slip-shipping",
      "sales-pre-invoicing-report",
      "collective-invoicing",
      "sales-cash-in-after-save",
    ],
  },
  {
    id: "buying",
    title: "Buying",
    description: "Purchase requests through supplier invoices.",
    articleIds: [
      "purchase-request-to-ap-flow",
      "purchase-request-load-slip-so",
      "rfq-workflow",
      "purchase-order-load-slip-pr",
      "purchase-order-load-slip-rfq",
      "goods-receipt-load-slip",
      "purchasing-load-slip-po",
      "supplier-invoice-load-slip-rfq",
      "purchase-pre-invoicing-report",
    ],
  },
  {
    id: "inventory",
    title: "Stock & serials",
    description: "Move, receive, issue stock, and scan serial numbers.",
    articleIds: [
      "transfer-stock-between-branches",
      "receive-stock-at-branch",
      "issue-stock-from-branch",
      "serial-barcode-scanning",
      "serial-lot-registry",
    ],
  },
  {
    id: "pos",
    title: "Point of Sale",
    description: "Retail checkout, serial scanning, and shift management.",
    articleIds: ["pos-checkout-guide", "pos-manage-settings"],
  },
  {
    id: "finance",
    title: "Accounts & finance",
    description: "Receipts, vouchers, GL, and reporting.",
    articleIds: [
      "finance-accounts-overview",
      "receivable-payable-status",
      "customer-vendor-book-report",
      "acct-vs-inventory-reconciliation",
    ],
  },
  {
    id: "operations",
    title: "Operations & CRM",
    description: "CRM, after-sales, shipping, quality, support, and HR.",
    articleIds: [
      "crm-follow-ups",
      "after-sales-repair",
      "support-tickets",
      "wms-and-shipping",
      "quality-ncr-capa",
      "hr-payroll-basics",
      "fixed-assets-register",
      "customer-portal",
    ],
  },
  {
    id: "advanced",
    title: "Advanced modules",
    description: "WMS, Data Center, manufacturing, job costing, and approvals.",
    articleIds: [
      "wms-scheduled-receipts",
      "data-center-ingestion",
      "manufacturing-bom",
      "job-costing-projects",
      "approvals-queue",
      "activity-logs-audit",
    ],
  },
  {
    id: "insights",
    title: "Dashboard & reconciliation",
    description: "KPIs, reports, and fixing data gaps.",
    articleIds: ["reports-and-dashboard", "stock-reconciliation-walkthrough", "sales-pre-invoicing-report", "purchase-pre-invoicing-report"],
  },
];
