import type { KbGroup } from "./documentationTypes";

export const knowledgebaseGroups: KbGroup[] = [
  {
    id: "account",
    title: "Account & businesses",
    description: "One login, multiple company workspaces, and invites.",
    articleIds: [
      "add-another-business",
      "switch-between-businesses",
      "join-business-by-invite",
      "switch-tenant-vs-branch",
    ],
  },
  {
    id: "getting-started",
    title: "Getting started",
    description: "First-time workspace setup and daily basics.",
    articleIds: [
      "start-90-day-trial",
      "setup-wizard",
      "process-policies-foundation",
      "process-policy-gates-explained",
      "foundation-setup-blocked-api",
      "cannot-confirm-document",
      "quotation-rfq-unregistered-products",
      "attachment-requirements",
      "document-attachments-workflow",
      "skip-setup-remind-later",
      "invited-during-setup",
      "onboarding-playbook",
      "load-slip-overview",
      "mapping-center-when-to-use",
      "migration-center",
      "inventory-master-data",
      "user-management-admin",
      "missing-menu-permission",
      "form-field-settings",
      "inline-custom-fields",
      "custom-field-required-block",
      "tax-and-currency",
      "demo-data-training",
      "demo-data-golden-scenarios",
      "write-permission-vs-read",
      "print-or-pdf-failed",
      "session-or-signin-issues",
      "tax-wrong-on-document",
    ],
  },
  {
    id: "branches",
    title: "Branches & locations",
    description: "Set up warehouses or branches and choose which one you are working in.",
    articleIds: ["add-branch", "switch-active-branch", "multi-branch-defaults", "empty-list-wrong-branch"],
  },
  {
    id: "selling",
    title: "Selling",
    description: "Quotations, sales orders, sales invoices, and group invoicing.",
    articleIds: [
      "quotation-to-sales-flow",
      "quotation-progress-status",
      "quotation-rfq-unregistered-products",
      "quotation-rfq-ai-import",
      "sales-order-release",
      "insufficient-stock-on-release",
      "delivery-receipt-vs-shipping",
      "sales-order-load-slip-quotation",
      "sales-load-slip-quotation",
      "sales-load-slip-so",
      "sales-load-slip-shipping",
      "load-slip-no-lines",
      "sales-shipping-from-line",
      "sales-hold-list",
      "sales-hold-list-resume",
      "sales-pre-invoicing-report",
      "collective-invoicing",
      "collective-invoice-edge-cases",
      "sales-cash-in-after-save",
      "official-receipt-after-si",
      "sales-return-serial",
      "sales-return-vs-repair-rma",
    ],
  },
  {
    id: "buying",
    title: "Buying",
    description: "Purchase requests through supplier invoices.",
    articleIds: [
      "purchase-request-to-ap-flow",
      "purchase-request-load-slip-so",
      "pr-approval-stuck",
      "rfq-workflow",
      "purchase-order-load-slip-pr",
      "purchase-order-load-slip-rfq",
      "po-confirm-from-list",
      "goods-receipt-load-slip",
      "goods-receipt-serial-receive",
      "purchasing-load-slip-po",
      "supplier-invoice-load-slip-rfq",
      "purchase-pre-invoicing-report",
      "purchase-cash-payment-after-save",
      "payment-voucher-after-purchase",
      "load-slip-no-lines",
    ],
  },
  {
    id: "inventory",
    title: "Stock & serials",
    description: "Move, receive, issue stock, and scan serial numbers.",
    articleIds: [
      "transfer-stock-between-branches",
      "receive-stock-at-branch",
      "issue-stock-from-branch",
      "serial-barcode-scanning",
      "serial-count-mismatch",
      "serial-not-found-sale",
      "serial-lot-registry",
      "item-serial-lot-tab",
      "find-inventory-record-history",
      "sales-lot-batch-pick",
      "lot-expiry-pick-rules",
      "insufficient-stock-on-release",
    ],
  },
  {
    id: "pos",
    title: "Point of Sale",
    description: "Retail checkout, serial scanning, and shift management.",
    articleIds: ["pos-checkout-guide", "pos-manage-settings", "pos-cannot-open-shift"],
  },
  {
    id: "finance",
    title: "Accounts & finance",
    description: "Receipts, vouchers, GL, and reporting.",
    articleIds: [
      "finance-accounts-overview",
      "chart-of-accounts-ph-template",
      "coa-soft-delete-restore",
      "finance-je-draft-to-post",
      "je-wont-post",
      "bank-reconciliation-weekly",
      "bank-rec-unmatched-lines",
      "receivable-payable-status",
      "customer-vendor-book-report",
      "acct-vs-inventory-reconciliation",
      "fixed-assets-depreciation-basics",
    ],
  },
  {
    id: "operations",
    title: "Operations & CRM",
    description: "Work Hub, CRM follow-ups, communications, after-sales, and support.",
    articleIds: [
      "operations-hub-intro",
      "operations-packs-edit",
      "operations-calendar-day-today",
      "calendar-drag-and-reminders",
      "work-item-link-erp-doc",
      "crm-operations-tasks-sync",
      "communications-overview",
      "document-email-workflow",
      "gmail-comms-connect",
      "crm-follow-ups",
      "after-sales-repair",
      "sales-return-vs-repair-rma",
      "support-tickets",
      "support-ticket-from-after-sales",
      "booking-services",
      "wms-and-shipping",
      "quality-ncr-capa",
      "quality-ncr-capa-loop",
      "hr-payroll-basics",
      "hr-payroll-run-basics",
      "fixed-assets-register",
      "customer-portal",
      "customer-portal-what-they-see",
    ],
  },
  {
    id: "advanced",
    title: "Advanced modules",
    description: "WMS, Data Center, manufacturing, job costing, and approvals.",
    articleIds: [
      "wms-scheduled-receipts",
      "wms-scheduled-receipt-variance",
      "data-center-ingestion",
      "data-center-import-errors",
      "manufacturing-bom",
      "mfg-recipe-assembly-shortage",
      "mfg-cutting-shortage",
      "mfg-waste-reason-required",
      "manufacturing-wo-issue-complete",
      "job-costing-projects",
      "job-costing-link-expenses",
      "approvals-queue",
      "activity-logs-audit",
    ],
  },
  {
    id: "insights",
    title: "Dashboard & reconciliation",
    description: "KPIs, reports, and fixing data gaps.",
    articleIds: [
      "reports-and-dashboard",
      "where-status-reports-live",
      "bi-reports-overview",
      "stock-reconciliation-walkthrough",
      "sales-pre-invoicing-report",
      "purchase-pre-invoicing-report",
    ],
  },
];
