package pdf

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf/v2"
)

// PrintChrome is tenant receipt branding applied to PDF headers/footers.
type PrintChrome struct {
	CompanyName string
	HeaderText  string
	FooterText  string
	Address     string
	Phone       string
	Email       string
	LogoData    []byte
	LogoType    string // PNG, JPG, GIF
}

func (c PrintChrome) footerOrDefault(fallback string) string {
	if strings.TrimSpace(c.FooterText) != "" {
		return strings.TrimSpace(c.FooterText)
	}
	if strings.TrimSpace(fallback) != "" {
		return strings.TrimSpace(fallback)
	}
	return "Generated by BluearmERP"
}

func (c PrintChrome) companyOr(fallback string) string {
	if strings.TrimSpace(c.CompanyName) != "" {
		return strings.TrimSpace(c.CompanyName)
	}
	return fallback
}

// RenderBrandedHeader draws logo (optional), company name, header meta, then doc title/subtitle.
func (d *DocLayout) RenderBrandedHeader(title, subtitle, fallbackCompany string, chrome PrintChrome) {
	company := chrome.companyOr(fallbackCompany)
	if len(chrome.LogoData) > 0 {
		imgType := chrome.LogoType
		if imgType == "" {
			imgType = "PNG"
		}
		opt := gofpdf.ImageOptions{ImageType: imgType, ReadDpi: true}
		info := d.pdf.RegisterImageOptionsReader("brand-logo", opt, bytes.NewReader(chrome.LogoData))
		if info != nil {
			h := 14.0
			if info.Width() > 0 {
				h = 28 * info.Height() / info.Width()
				if h > 18 {
					h = 18
				}
			}
			d.pdf.ImageOptions("brand-logo", pageMargin, d.y, 28, 0, false, opt, 0, "")
			d.y += h + 2
		}
	}
	d.pdf.SetFont("Arial", "B", 16)
	d.pdf.SetXY(pageMargin, d.y)
	d.pdf.CellFormat(0, 8, company, "", 1, "L", false, 0, "")
	d.y += 8
	if meta := strings.TrimSpace(chrome.HeaderText); meta != "" {
		d.pdf.SetFont("Arial", "", 9)
		d.pdf.SetTextColor(80, 80, 80)
		for _, line := range strings.Split(meta, "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			d.pdf.SetXY(pageMargin, d.y)
			d.pdf.MultiCell(0, 4.5, line, "", "L", false)
			d.y = d.pdf.GetY()
		}
		d.pdf.SetTextColor(0, 0, 0)
		d.y += 2
	}
	d.pdf.SetFont("Arial", "B", 14)
	d.pdf.SetXY(pageMargin, d.y)
	d.pdf.CellFormat(0, 7, title, "", 1, "L", false, 0, "")
	d.y += 7
	if subtitle != "" {
		d.pdf.SetFont("Arial", "", 11)
		d.pdf.SetXY(pageMargin, d.y)
		d.pdf.CellFormat(0, 6, subtitle, "", 1, "L", false, 0, "")
		d.y += 6
	}
	d.y += 4
}

// ApplyChromeToParty overlays branding company/contact onto a Party used as “from” identity.
func ApplyChromeToParty(p *Party, chrome PrintChrome) {
	if chrome.CompanyName != "" {
		p.CompanyName = chrome.CompanyName
	}
	if chrome.Address != "" {
		p.Address = chrome.Address
	}
	if chrome.Phone != "" {
		p.Phone = chrome.Phone
	}
	if chrome.Email != "" {
		p.Email = chrome.Email
	}
}

// DefaultGeneratedFooter builds the legacy timestamp footer when branding footer is empty.
func DefaultGeneratedFooter(at time.Time) string {
	return fmt.Sprintf("Generated from BluearmERP · %s", at.Format("2006-01-02 15:04"))
}
