package pdf

import "fmt"

// GenericDocumentInput renders any ERP document with shared layout primitives.
type GenericDocumentInput struct {
	DocTitle          string
	DocSubtitle       string
	Tenant            Party
	CounterpartyTitle string
	Counterparty      Party
	DetailFields      []PartyField
	LineHeaders       []string
	LineRows          [][]string
	LineColWidths     []float64
	Totals            []TotalRow
	Notes             string
}

// RenderGenericDocumentPDF builds a PDF from GenericDocumentInput.
func RenderGenericDocumentPDF(in GenericDocumentInput) ([]byte, error) {
	d := NewDocLayout()
	d.RenderHeader(in.DocTitle, in.DocSubtitle, in.Tenant.CompanyName)

	if len(in.DetailFields) > 0 {
		d.RenderParty("Details", in.DetailFields)
	}

	cpTitle := in.CounterpartyTitle
	if cpTitle == "" {
		cpTitle = "Party"
	}
	d.RenderParty(cpTitle, partyFields(in.Counterparty))

	if len(in.LineHeaders) > 0 && len(in.LineRows) > 0 {
		d.RenderLineTable(in.LineHeaders, in.LineRows, in.LineColWidths)
	}
	if len(in.Totals) > 0 {
		d.RenderTotals(in.Totals)
	}
	if in.Notes != "" {
		d.RenderTextBlock("Notes", in.Notes)
	}
	d.RenderFooter("Generated by BluearmERP")
	return d.Bytes()
}

func partyFields(p Party) []PartyField {
	fields := []PartyField{{Label: "Name", Value: p.CompanyName}}
	if p.Address != "" {
		fields = append(fields, PartyField{Label: "Address", Value: p.Address})
	}
	contact := p.Phone
	if p.Mobile != "" {
		if contact != "" {
			contact += " · "
		}
		contact += p.Mobile
	}
	if p.Email != "" {
		if contact != "" {
			contact += " · "
		}
		contact += p.Email
	}
	if contact != "" {
		fields = append(fields, PartyField{Label: "Contact", Value: contact})
	}
	return fields
}

func FormatMoney(amount float64, currencyCode string) string {
	s := fmt.Sprintf("%.2f", amount)
	if currencyCode != "" {
		return currencyCode + " " + s
	}
	return s
}
