-- Full chart of accounts seed.
-- The prior seed (063) inferred account_type from the leading digit, which
-- mislabels the 3-digit "Sales: ..." (210-235 = income) and "Purchase: ..."
-- (310-334 = expense) ranges, and the mixed 2xxx asset/liability ranges.
-- This migration installs the complete, correctly-typed COA via a reusable
-- function so existing tenants, new tenants, and demo tenants all get it.
begin;

create or replace function public.seed_tenant_chart_of_accounts(p_tenant bigint)
returns void
language plpgsql
as $$
begin
  insert into public.fin_accounts (tenant_id, account_code, account_name, account_type, sort_order)
  select p_tenant, v.code, v.name, v.atype, (row_number() over ())::int * 10
  from (values
    -- Assets (1xxx)
    ('1020','Cash on Hand','asset'),
    ('1021','CCB Cash On Hand','asset'),
    ('1022','MCB Cash On Hand','asset'),
    ('1023','UnionBank - 7610','asset'),
    ('1024','GCASH - 0013','asset'),
    ('1025','Security Bank - 4050','asset'),
    ('1026','BDO - 2888','asset'),
    ('1028','Home Credit - Unionbank 7610','asset'),
    ('1029','Checking Accounts','asset'),
    ('1030','Savings Accounts','asset'),
    ('1031','Installment Savings','asset'),
    ('1032','Billease - Unionbank - 7610','asset'),
    ('1033','Paymongo - Unionbank 7610','asset'),
    ('1034','Paypal - Unionbank 7610','asset'),
    ('1059','Trading Securities','asset'),
    ('1064','Available-for-Sale Securities','asset'),
    ('1071','Held-to-Maturity Securities','asset'),
    ('1072','Marketable Securities','asset'),
    ('1073','Other Short-term Investments','asset'),
    ('1089','Accounts Receivable','asset'),
    ('1099','Allowance for Bad Debts - A／R','asset'),
    ('1109','Notes Receivable','asset'),
    ('1119','Allowance for Bad Debts - N／R','asset'),
    ('1149','Other Receivables','asset'),
    ('1169','Unearned Interest','asset'),
    ('1170','Undeposited Funds','asset'),
    ('1318','Due from Subsidiaries','asset'),
    ('1319','Advances to Vendors','asset'),
    ('1339','Prepaid Expenses','asset'),
    ('1349','Advances to Employees','asset'),
    ('1359','VAT Paid to Vendors','asset'),
    ('1369','Prepaid Taxes','asset'),
    ('1379','Short-term Loans to Stock Holder, Executive, Employees','asset'),
    ('1469','Merchandise','asset'),
    ('1509','Finished Goods','asset'),
    ('1539','Raw Materials','asset'),
    ('1689','Goods in transit','asset'),
    ('1699','Work In Process','asset'),
    ('1799','Long-term Loan Receivables','asset'),
    ('1809','Allowance for Bad Debts - L／R','asset'),
    ('1819','Long-term Receivables','asset'),
    ('1889','Security Deposit Paid','asset'),
    ('1924','Investments in Unused Land','asset'),
    ('1969','Deferred Tax Assets','asset'),
    -- Income: Sales categories (3-digit 2xx)
    ('210','Sales: Motherboard','income'),
    ('211','Sales: RAM','income'),
    ('212','Sales: Processor','income'),
    ('213','Sales: Monitors','income'),
    ('214','Sales: Laptop','income'),
    ('215','Sales: CCTV','income'),
    ('216','Sales: Computer Package','income'),
    ('217','Sales: Printer','income'),
    ('218','Sales: Keyboard','income'),
    ('219','Sales: Mouse','income'),
    ('220','Sales: Storage','income'),
    ('221','Sales: GPU','income'),
    ('222','Sales: Casing','income'),
    ('223','Sales: Headset/Speakers','income'),
    ('224','Sales: All In One PC','income'),
    ('225','Sales: Mobile Phones','income'),
    ('226','Sales: Computer Table','income'),
    ('227','Sales: Gaming Chairs','income'),
    ('228','Sales: PSU','income'),
    ('229','Sales: Routers','income'),
    ('230','Sales: Projectors','income'),
    ('231','Sales: Softwares','income'),
    ('232','Sales: Tablets','income'),
    ('233','Sales: Peripherals','income'),
    ('234','Sales: RMA','income'),
    ('235','Sales: Services','income'),
    -- Property, plant & equipment and intangibles (4-digit 2xxx assets)
    ('2019','Land','asset'),
    ('2029','Buildings','asset'),
    ('2039','Accu. Depreciation - Buildings','asset'),
    ('2049','Building Improvements','asset'),
    ('2059','Accu. Depreciation - Building Improvements','asset'),
    ('2069','Machinery and Equipment','asset'),
    ('2079','Accu. Depreciation - Machinery And Equipment','asset'),
    ('2089','Vehicles','asset'),
    ('2099','Accu. Depreciation - Vehicles','asset'),
    ('2109','Furniture and Fixtures','asset'),
    ('2119','Accu. Depreciation - Furniture And Fixtures','asset'),
    ('2129','Office Equipment','asset'),
    ('2139','Accu. Depreciation - Office Equipment','asset'),
    ('2149','Buildings in Process','asset'),
    ('2199','Computer Equipment','asset'),
    ('2209','Accu. Depreciation - Computer Equipment','asset'),
    ('2219','Other Property, Plant, and Equipment','asset'),
    ('2229','Accu. Depreciation - Other PPE','asset'),
    ('2239','Leasehold Improvements','asset'),
    ('2249','Accu. Depreciation - Leasehold Improvements','asset'),
    ('2319','Goodwill','asset'),
    ('2329','Patents','asset'),
    ('2399','Trademarks','asset'),
    ('2401','Copyrights','asset'),
    ('2409','Computer Software','asset'),
    ('2458','Long-Term Other Receivables','asset'),
    -- Liabilities (4-digit 2xxx)
    ('2519','Accounts Payable','liability'),
    ('2529','Notes Payable','liability'),
    ('2539','Non-trade Payables','liability'),
    ('2540','Credit Card Payable','liability'),
    ('2549','Payroll Tax Liabilities','liability'),
    ('2559','Sales Tax Payable','liability'),
    ('2569','Due to Subsidiaries','liability'),
    ('2609','Short-term Loans','liability'),
    ('2610','Security Deposit Received','liability'),
    ('2611','Uncleared Payments','liability'),
    ('2619','Unpaid Taxes','liability'),
    ('2629','Unpaid Expenses','liability'),
    ('2639','Unearned Revenues','liability'),
    ('2649','Unpaid Wages','liability'),
    ('2739','Deferred Tax Liabilities - ST','liability'),
    ('2939','Long-term Loans','liability'),
    -- Expense: Purchase categories (3-digit 3xx)
    ('310','Purchase: Motherboard','expense'),
    ('311','Purchase: RAM','expense'),
    ('312','Purchase: Processor','expense'),
    ('313','Purchase: Monitors','expense'),
    ('314','Purchase: Laptop','expense'),
    ('315','Purchase: CCTV','expense'),
    ('316','Purchase: Computer Package','expense'),
    ('317','Purchase: Printer','expense'),
    ('318','Purchase: Keyboard','expense'),
    ('319','Purchase: Mouse','expense'),
    ('320','Purchase: Storage','expense'),
    ('321','Purchase: GPU','expense'),
    ('322','Purchase: Casing','expense'),
    ('323','Purchase: Headset/Speakers','expense'),
    ('324','Purchase: All In One PC','expense'),
    ('325','Purchase: Mobile Phones','expense'),
    ('326','Purchase: Computer Table','expense'),
    ('327','Purchase: Gaming Chairs','expense'),
    ('328','Purchase: PSU','expense'),
    ('329','Purchase: Routers','expense'),
    ('330','Purchase: Projectors','expense'),
    ('331','Purchase: Softwares','expense'),
    ('332','Purchase: Tablets','expense'),
    ('333','Purchase: Peripherals','expense'),
    ('334','Purchase: Services','expense'),
    -- Equity and long-term deferred tax (4-digit 3xxx)
    ('3109','Deferred Tax Liabilities - LT','liability'),
    ('3329','Common Stock','equity'),
    ('3333','Preferred Stock','equity'),
    ('3339','Common Stock Subscribed','equity'),
    ('3353','Paid-In Capital in Excess of Par','equity'),
    ('3356','Gain on Retirement of Stock','equity'),
    ('3359','Any Other Gain on Stock Transactions','equity'),
    ('3389','Treasury Stock','equity'),
    ('3429','Gain or Loss on Available-For-Sale Securities','equity'),
    ('3519','Appropriated Retained Earnings','equity'),
    ('3779','Retained Earnings from Previous Year','equity'),
    ('3799','(Net Income)','equity'),
    -- Income (4xxx)
    ('4019','Sales - Merchandise','income'),
    ('4029','Sales Returns and Allowances','income'),
    ('4039','Sales Discounts','income'),
    ('4049','Sales - Finished goods','income'),
    ('4119','Sales - Service','income'),
    ('4559','Purchase Returns and Alloawances','expense'),
    ('4569','Purchase Discount','expense'),
    -- Manufacturing expenses (5xxx)
    ('5028','Raw Material Expenses','expense'),
    ('5039','Payroll Expenses(Mfg.)','expense'),
    ('5049','Supervision Salaries(Mfg.)','expense'),
    ('5059','Bonuses(Mfg.)','expense'),
    ('5069','Fringe Benefits(Mfg.)','expense'),
    ('5079','Part-Time Salaries(Mfg.)','expense'),
    ('5099','Severance Pay(Mfg.)','expense'),
    ('5109','Employee Benefits(Mfg.)','expense'),
    ('5119','Travel＆Lodging(Mfg.)','expense'),
    ('5129','Entertainment(Mfg.)','expense'),
    ('5139','Telephone(Mfg.)','expense'),
    ('5149','R＆D Expenses(Mfg.)','expense'),
    ('5209','Utilities(Mfg.)','expense'),
    ('5219','Taxes Other Than Income Tax(Mfg.)','expense'),
    ('5229','Depreciation Expenses(Mfg.)','expense'),
    ('5239','Rent Expenses(Mfg.)','expense'),
    ('5249','Repairing Expenses(Mfg.)','expense'),
    ('5259','Insurance Expenses(Mfg.)','expense'),
    ('5269','Automobile Expenses(Mfg.)','expense'),
    ('5279','Training And Education(Mfg.)','expense'),
    ('5299','Packing Expenses(Mfg.)','expense'),
    ('5309','Office Supplies(Mfg.)','expense'),
    ('5319','Service Fees(Mfg.)','expense'),
    ('5339','Outsourcing Expenses(Mfg.)','expense'),
    ('5349','Electricity(Mfg.)','expense'),
    ('5369','Freight Charge(Mfg.)','expense'),
    ('5379','Misc. Expenses(Mfg.)','expense'),
    -- Selling & administrative expenses (8xxx)
    ('8019','Payroll-Officers(S＆A)','expense'),
    ('8029','Payroll-Employee(S＆A)','expense'),
    ('8039','Bonuses(S＆A)','expense'),
    ('8049','Fringe Benefits(S＆A)','expense'),
    ('8059','Part-Time Salaries(S＆A)','expense'),
    ('8089','Severance Pay(S＆A)','expense'),
    ('8109','Employee Benefits(S＆A)','expense'),
    ('8119','Travel＆Lodging(S＆A)','expense'),
    ('8129','Entertainment(S＆A)','expense'),
    ('8139','Telephone(S＆A)','expense'),
    ('8149','R＆D Expenses(S＆A)','expense'),
    ('8229','Taxes Other Than Income Tax(S＆A)','expense'),
    ('8239','Depreciation Expenses(S＆A)','expense'),
    ('8249','Rent Expenses(S＆A)','expense'),
    ('8259','Repairing Expenses(S＆A)','expense'),
    ('8269','Insurance Expenses(S＆A)','expense'),
    ('8279','Automobile Expenses(S＆A)','expense'),
    ('8289','Training And Education(S＆A)','expense'),
    ('8299','Office Supplies(S＆A)','expense'),
    ('8309','Utilities(S＆A)','expense'),
    ('8319','Professional Service Fees(S＆A)','expense'),
    ('8338','Advertising Expenses(S＆A)','expense'),
    ('8339','Outsourcing Expenses(S＆A)','expense'),
    ('8349','Sales Promotion Expenses(S＆A)','expense'),
    ('8359','Bad Debt Expenses(S＆A)','expense'),
    ('8369','Building Maintenance(S＆A)','expense'),
    ('8379','Freight Charge(S＆A)','expense'),
    ('8399','Sales Commission(S＆A)','expense'),
    ('8404','Food(S＆A)','expense'),
    ('8409','Amortization Expenses(S＆A)','expense'),
    ('8489','Payroll Tax Expenses(S＆A)','expense'),
    ('8490','Misc. Expenses(S＆A)','expense'),
    -- Other income (9xxx gains/revenue)
    ('9019','Interest Revenue','income'),
    ('9029','Interest on Securities','income'),
    ('9039','Dividend','income'),
    ('9049','Rent Revenue','income'),
    ('9059','Gain on Correction of Error','income'),
    ('9069','Impairment Gain-Securities','income'),
    ('9072','Estimated Gain-Securities','income'),
    ('9079','Gain on Foreign Translation','income'),
    ('9095','Unrealized Gain on Equity Method','income'),
    ('9149','Gain on Sale of PPE','income'),
    ('9159','Gain on Sale of Securities','income'),
    ('9199','Other Gains','income'),
    -- Other expenses (9xxx losses/taxes)
    ('9319','Interest Expenses','expense'),
    ('9320','Transaction Fee','expense'),
    ('9329','Loss on Foreign Translation','expense'),
    ('9349','Other Amortization','expense'),
    ('9359','Loss on Correction of Error','expense'),
    ('9369','Donations','expense'),
    ('9379','Unrealized Loss on Equity Method','expense'),
    ('9389','Impairment Loss-Securities','expense'),
    ('9395','Estimated Loss-Securities','expense'),
    ('9399','Impairment Loss-Inventories','expense'),
    ('9409','Estimated Loss-Inventories','expense'),
    ('9509','Loss on Sale of PPE','expense'),
    ('9519','Loss on Sale of Securities','expense'),
    ('9549','Other Losses','expense'),
    ('9719','Income Taxes','expense')
  ) as v(code, name, atype)
  on conflict (tenant_id, account_code) do nothing;
end;
$$;

-- Backfill every existing active tenant.
do $$
declare t record;
begin
  for t in select id from public.tenants where status = 'active' loop
    perform public.seed_tenant_chart_of_accounts(t.id);
  end loop;
end $$;

-- Keep the global GL picklist in sync (names) from the freshly seeded accounts.
insert into public.fin_gl_accounts (account_code, account_name, sort_order)
select account_code, min(account_name), min(sort_order)
from public.fin_accounts
group by account_code
on conflict (account_code) do update
  set account_name = excluded.account_name;

commit;
