#!/usr/bin/env python3
"""
Gate G6: reverse-map Bluearm shell routes from modules.ts (+ App.tsx Route paths)
against coverage-matrix bluearm_route values. Emits bluearm-orphan-report.md.

Usage:
  python bluearm-orphan-map.py
  python bluearm-orphan-map.py --check   # exit 1 if report cannot be written / parse fails
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

AUDIT = Path(__file__).resolve().parents[1]
ROOT = AUDIT.parents[1]  # bluearmerp-v3
MATRIX = AUDIT / "coverage-matrix.csv"
MODULES = ROOT / "web" / "src" / "shell" / "modules.ts"
APP = ROOT / "web" / "src" / "App.tsx"
REPORT = AUDIT / "bluearm-orphan-report.md"
REVERSE = AUDIT / "bluearm-route-reverse.csv"

HREF_RE = re.compile(r'href:\s*"(/app/[^"]+)"')
ROUTE_RE = re.compile(r'path="(/[^"]+)"')
BASE_RE = re.compile(r'basePath:\s*"(/app/[^"]+)"')


def collect_shell_hrefs() -> set[str]:
    text = MODULES.read_text(encoding="utf-8")
    hrefs = set(HREF_RE.findall(text))
    hrefs |= set(BASE_RE.findall(text))
    return hrefs


def collect_app_routes() -> set[str]:
    if not APP.exists():
        return set()
    text = APP.read_text(encoding="utf-8")
    paths = set()
    for p in ROUTE_RE.findall(text):
        if p.startswith("/app") or p.startswith("/portal"):
            paths.add(p if p.startswith("/app") else p)
        elif p.startswith("/") and not p.startswith("//"):
            # App.tsx often nests under /app via parent; keep /app-prefixed only
            if "app" in p:
                paths.add(p)
    # Also capture template paths like /dashboard under Route parent /app
    for m in re.finditer(r'<Route\s+path="([^"]+)"', text):
        p = m.group(1)
        if p.startswith("/"):
            if p.startswith("/app") or p.startswith("/portal") or p.startswith("/login"):
                paths.add(p)
            else:
                # relative to /app in many files — normalize
                if not p.startswith("/api"):
                    paths.add("/app" + p if not p.startswith("/app") else p)
    return paths


def normalize(path: str) -> str:
    p = path.strip().rstrip("/")
    if not p:
        return ""
    # strip query
    p = p.split("?")[0]
    return p


def matrix_routes() -> dict[str, list[str]]:
    """route -> [prgIds]"""
    by: dict[str, list[str]] = {}
    with MATRIX.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            route = normalize(row.get("bluearm_route") or "")
            if not route or route in ("—", "-"):
                continue
            by.setdefault(route, []).append(row.get("prgId") or "")
    return by


def main() -> None:
    check = "--check" in sys.argv
    shell = {normalize(h) for h in collect_shell_hrefs()}
    app_routes = {normalize(h) for h in collect_app_routes()}
    bluearm = shell | {r for r in app_routes if r.startswith("/app")}
    mapped = matrix_routes()
    mapped_set = set(mapped.keys())

    # Orphan = Bluearm /app route in shell with no matrix row pointing at it (exact or prefix parent)
    def covered(route: str) -> bool:
        if route in mapped_set:
            return True
        for m in mapped_set:
            if route.startswith(m + "/") or m.startswith(route + "/"):
                return True
        return False

    orphans = sorted(r for r in shell if r.startswith("/app") and not covered(r))
    # Unmapped matrix routes (point to /app but not in shell) — informational
    matrix_only = sorted(
        r for r in mapped_set if r.startswith("/app") and r not in shell and not any(r.startswith(s + "/") for s in shell)
    )

    lines = [
        "# Bluearm orphan report (Gate G6)",
        "",
        f"_Generated by `scripts/bluearm-orphan-map.py`._",
        "",
        f"| Metric | Count |",
        f"|--------|------:|",
        f"| Shell hrefs (`modules.ts`) | {len(shell)} |",
        f"| App.tsx /app-ish routes (heuristic) | {len(app_routes)} |",
        f"| Distinct matrix `bluearm_route` values | {len(mapped_set)} |",
        f"| **Orphans** (shell href with no matrix cover) | **{len(orphans)}** |",
        f"| Matrix routes not in shell | {len(matrix_only)} |",
        "",
        "## Orphans (need reverse-map row or intentional Bluearm-only note)",
        "",
    ]
    if orphans:
        lines.append("| route | action |")
        lines.append("|-------|--------|")
        for r in orphans:
            lines.append(f"| `{r}` | Add coverage reverse note or mark Bluearm-only in reverse CSV |")
    else:
        lines.append("_None — every shell href is covered by a matrix route (exact or prefix)._")
    lines += [
        "",
        "## Matrix routes without shell href (may still be valid deep links)",
        "",
        f"Count: {len(matrix_only)} (showing first 40)",
        "",
        "| route | prgIds (sample) |",
        "|-------|-----------------|",
    ]
    for r in matrix_only[:40]:
        pids = ", ".join(mapped[r][:4])
        lines.append(f"| `{r}` | {pids} |")
    lines += [
        "",
        "## Gate G6",
        "",
        "G6 passes when orphan count is reviewed and each orphan is either mapped in coverage-matrix "
        "or listed in `bluearm-route-reverse.csv` with `kind=bluearm_only`.",
        "",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")

    # Reverse CSV: all shell hrefs
    with REVERSE.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["bluearm_route", "kind", "prgIds", "notes"])
        w.writeheader()
        for r in sorted(shell):
            if covered(r):
                pids = []
                for m, ids in mapped.items():
                    if r == m or r.startswith(m + "/") or m.startswith(r + "/"):
                        pids.extend(ids)
                w.writerow(
                    {
                        "bluearm_route": r,
                        "kind": "mapped",
                        "prgIds": ";".join(sorted(set(pids))[:12]),
                        "notes": "",
                    }
                )
            else:
                w.writerow(
                    {
                        "bluearm_route": r,
                        "kind": "orphan",
                        "prgIds": "",
                        "notes": "No coverage-matrix bluearm_route cover — Bluearm-only or needs Ecount map",
                    }
                )

    print(f"Shell hrefs: {len(shell)}; orphans: {len(orphans)}; wrote {REPORT.name}, {REVERSE.name}")
    if check and not REPORT.exists():
        sys.exit(1)
    # Soft check: always exit 0 after generating report (orphans are expected for CRM/etc.)
    sys.exit(0)


if __name__ == "__main__":
    main()
