#!/usr/bin/env python3
"""Emit module-level parity rollup for Phase C status (does not invent depth-complete)."""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

AUDIT = Path(__file__).resolve().parents[1]
MATRIX = AUDIT / "coverage-matrix.csv"
OUT = AUDIT / "module-parity-status.md"

FOCUS = ("Inv. I", "Inv. II", "Acct. I", "Acct. II", "MyPage", "Mgmt", "GW", "Data Center")


def main() -> None:
    by_l1: dict[str, list[dict[str, str]]] = defaultdict(list)
    with MATRIX.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            by_l1[row.get("menu_path_l1") or "?"].append(row)

    lines = [
        "# Module parity status (Phase C rollup)",
        "",
        "_Generated by `scripts/module-parity-report.py`. Depth-complete requires live tab-pill crawl; this file only rolls up matrix fields._",
        "",
        "| Module (L1) | rows | depth-complete | parity | partial | missing | deferred |",
        "|-------------|-----:|---------------:|-------:|--------:|--------:|---------:|",
    ]
    for l1 in FOCUS:
        rows = by_l1.get(l1, [])
        if not rows:
            continue
        st = Counter(r.get("status") or "" for r in rows)
        pr = Counter(r.get("bluearm_parity") or "" for r in rows)
        lines.append(
            f"| {l1} | {len(rows)} | {st.get('depth-complete', 0)} | {pr.get('parity', 0)} | "
            f"{pr.get('partial', 0)} | {pr.get('missing', 0)} | {pr.get('deferred', 0)} |"
        )

    lines += [
        "",
        "## Priority work order (from plan)",
        "",
        "1. Inv. I Sales + Purchases + Setup Item — raise `partial` → residual gaps → `parity`",
        "2. Inv. I Inv. Mov. + Production/GR",
        "3. Inv. II Serial/Lot — verify known Done rows stay `parity`",
        "4. Acct. I Fast Entry / journals",
        "5. Acct. II AR/AP",
        "6. Reports trees",
        "7. Mgmt / GW / Data Center — stay on deferred-register unless licensed need",
        "",
        "## Gate reminder",
        "",
        "Do not claim a module complete unless G0–G3 pass for that module’s prgIds (see scorecard.md).",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
