/** Maps app routes to permission_registry codes (must match migration 020). */
export const hrefPermissionCode: Record<string, string> = {
  "/app/dashboard": "dashboard.view",
  "/app/inventory/partners": "inventory.partners",
  "/app/inventory/locations": "inventory.locations",
  "/app/inventory/projects": "inventory.projects",
  "/app/inventory/departments": "inventory.departments",
  "/app/inventory/items": "inventory.items",
  "/app/inventory/stock-movements": "inventory.stock_movements",
  "/app/inventory/serial-lot/registry": "inventory.serial_registry",
  "/app/inventory/serial-lot/lots": "inventory.serial_registry",
  "/app/inventory/serial-lot/movements": "inventory.serial_movements",
  "/app/inventory/serial-lot/trace": "inventory.serial_trace",
  "/app/inventory/serial-lot/receive": "inventory.serial_receive",
  "/app/inventory/serial-lot/settings": "inventory.serial_settings",
  "/app/after-sales/repair-orders": "after_sales.repair_orders",
  "/app/after-sales/repair-orders/new": "after_sales.repair_orders_new",
  "/app/after-sales/repair-orders/status": "after_sales.repair_orders_status",
  "/app/after-sales/register-repair/new": "after_sales.register_repair_new",
  "/app/after-sales/register-repair": "after_sales.register_repair",
  "/app/after-sales/register-repair/status": "after_sales.register_repair_status",
  "/app/after-sales/register-repair/consumption": "after_sales.register_repair_consumption",
  "/app/quotation/quotations/new": "quotation.quotations_new",
  "/app/quotation/quotations": "quotation.quotations",
  "/app/quotation/quotations/status": "quotation.quotations_status",
  "/app/quotation/quotations/outstanding": "quotation.quotations_outstanding",
  "/app/quotation/tax-mngt/tax-types": "quotation.tax_types",
  "/app/quotation/tax-mngt/currencies": "quotation.currencies",
  "/app/sales-order/sales-orders/new": "sales_order.sales_orders_new",
  "/app/sales-order/sales-orders": "sales_order.sales_orders",
  "/app/sales-order/sales-orders/status": "sales_order.sales_orders_status",
  "/app/sales-order/sales-orders/outstanding": "sales_order.sales_orders_outstanding",
  "/app/sales-order/sales-orders/release": "sales_order.sales_orders_release",
  "/app/sales-order/delivery-receipts/new": "sales_order.delivery_receipts_new",
  "/app/sales-order/delivery-receipts": "sales_order.delivery_receipts",
  "/app/purchase-request/purchase-requests/new": "purchase_request.purchase_requests_new",
  "/app/purchase-request/purchase-requests": "purchase_request.purchase_requests",
  "/app/purchase-request/purchase-requests/status": "purchase_request.purchase_requests_status",
  "/app/purchase-request/purchase-requests/settings": "purchase_request.purchase_requests",
  "/app/purchase-request/purchase-orders": "purchase_order.purchase_orders",
  "/app/purchase-request/goods-receipt": "purchase_order.goods_receipts",
  "/app/sales/sales/new": "sales.sales_new",
  "/app/sales/sales": "sales.sales",
  "/app/sales/sales/status": "sales.sales_status",
  "/app/sales/sales/pre-invoicing": "sales.sales_pre_invoicing",
  "/app/sales/sales/price-batch": "sales.sales_price_batch",
  "/app/sales/reports/official-receipt-status": "sales.official_receipt_status",
  "/app/sales/reports/si-receipt-status": "sales.si_receipt_status",
  "/app/sales/reports/ar-by-customer": "sales.ar_by_customer",
  "/app/sales/reports/discount-status": "sales.sales_discount_status",
  "/app/sales/collective-invoicing/list": "sales.collective_invoice_list",
  "/app/sales/collective-invoicing/status": "sales.collective_invoice_status",
  "/app/sales/reports/print-slips": "sales.print_sales_slips",
  "/app/finance/official-receipts/new": "finance.official_receipts_new",
  "/app/finance/official-receipts": "finance.official_receipts",
  "/app/finance/supplier-invoices/new": "finance.supplier_invoices_new",
  "/app/finance/supplier-invoices": "finance.supplier_invoices",
  "/app/finance/payment-vouchers/new": "finance.payment_vouchers_new",
  "/app/finance/payment-vouchers": "finance.payment_vouchers",
  "/app/finance/reports/ar-by-customer": "finance.reports_ar_by_customer",
  "/app/finance/reports/ap-by-vendor": "finance.reports_ap_by_vendor",
  "/app/finance/reports/receipt-status": "finance.reports_receipt_status",
  "/app/finance/reports/supplier-payment-status": "finance.reports_supplier_payment_status",
  "/app/finance/reports/official-receipt-status": "finance.official_receipts",
  "/app/crm/dashboard": "crm.dashboard",
  "/app/crm/notifications": "crm.notifications",
  "/app/crm/follow-up-tasks": "crm.follow_up_tasks",
  "/app/crm/pipelines/quotations": "crm.pipelines_quotations",
  "/app/crm/warranty-assets": "crm.warranty_assets",
  "/app/crm/reports/customer-quotations": "crm.reports_customer_quotations",
  "/app/crm/reports/item-demand": "crm.reports_item_demand",
  "/app/crm/reports/conversion": "crm.reports_conversion",
  "/app/crm/reports/low-stock": "crm.reports_low_stock",
  "/app/crm/settings/alert-rules": "crm.settings_alert_rules",
  "/app/activity-logs": "activity_logs.logs",
  "/app/activity-logs/changes": "activity_logs.changes",
  "/app/user-management/users": "user_management.users",
  "/app/user-management/roles": "user_management.roles",
};

export function permissionCodeForHref(href: string): string | undefined {
  if (hrefPermissionCode[href]) return hrefPermissionCode[href];
  const base = href.replace(/\/settings$/, "").replace(/\/new$/, "");
  return hrefPermissionCode[base];
}

export function permissionCodeForModule(moduleId: string): string {
  return moduleId;
}
