#!/usr/bin/env python3
"""Generate seed-demo-sales-orders-export.sql from Sales Order List Excel export."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import openpyxl

from export_seed_common import (
    col_index,
    find_sheet,
    header_row_index,
    parse_date_no,
    parse_money,
    parse_us_date,
    sql_str,
)

TAX_RATE_DEFAULT = 0.12


def split_amounts(grand: float, rate: float = TAX_RATE_DEFAULT) -> tuple[float, float, float]:
    if grand <= 0 or rate <= 0:
        return grand, 0.0, grand
    subtotal = round(grand / (1 + rate), 4)
    tax = round(grand - subtotal, 4)
    return subtotal, tax, grand


def load_rows(xlsx: Path) -> list[dict]:
    wb = openpyxl.load_workbook(xlsx, read_only=True, data_only=True)
    sheet = find_sheet(wb, ["Sales Order List", "Sales Orders", "Sales Order"], "Sales Order No")
    ws = wb[sheet]
    hdr_idx = header_row_index(ws, ("Sales Order No", "Customer Name"))
    headers = next(ws.iter_rows(min_row=hdr_idx, max_row=hdr_idx, values_only=True))
    i_date_no = col_index(headers, "Date-No", "Date No")
    i_so_no = col_index(headers, "Sales Order No", "Sales Order No.")
    i_customer = col_index(headers, "Customer Name", "Customer")
    i_item = col_index(headers, "Item Name", "Item Name (Summary)")
    i_delivery = col_index(headers, "Delivery Date")
    i_amount = col_index(headers, "Total Sales Order Amount", "Grand Total", "Total")
    i_progress = col_index(headers, "Progress Status", "Progress")
    i_pic = col_index(headers, "PIC Name", "PIC")
    i_remarks = col_index(headers, "Delivery Remarks", "Remarks")
    i_payment = col_index(headers, "Payment Terms", "MOP")
    if i_so_no is None or i_customer is None:
        raise ValueError(f"missing required columns in headers: {headers}")

    out: list[dict] = []
    for row in ws.iter_rows(min_row=hdr_idx + 1, values_only=True):
        if not row or row[i_so_no] in (None, ""):
            continue
        so_no = re.sub(r"\s+", "", str(row[i_so_no]).strip())
        customer = str(row[i_customer] or "").strip()
        if not customer:
            continue
        date_no_raw = str(row[i_date_no]).strip() if i_date_no is not None and row[i_date_no] else ""
        if date_no_raw:
            order_date, date_seq = parse_date_no(date_no_raw)
        else:
            m = re.match(r"^(\d{6})(\d{3})$", so_no)
            if not m:
                continue
            yy, mm, dd = int(m.group(1)[0:2]), int(m.group(1)[2:4]), int(m.group(1)[4:6])
            order_date = __import__("datetime").date(2000 + yy, mm, dd)
            date_seq = int(m.group(2))
        amount = parse_money(row[i_amount] if i_amount is not None else None)
        if amount is None:
            amount = 0.0
        subtotal, tax_total, grand_total = split_amounts(amount)
        progress_raw = str(row[i_progress] if i_progress is not None else "In Progress").strip().lower()
        if progress_raw == "completed":
            progress = "completed"
        elif progress_raw == "in progress":
            progress = "in_progress"
        else:
            progress = "unconfirmed"
        delivery = parse_us_date(row[i_delivery] if i_delivery is not None else None)
        out.append(
            {
                "order_date": order_date,
                "date_seq": date_seq,
                "sales_order_no": so_no,
                "customer": customer,
                "item_summary": str(row[i_item] or "").strip()[:1000],
                "delivery_date": delivery,
                "subtotal": subtotal,
                "tax_total": tax_total,
                "grand_total": grand_total,
                "progress_status": progress,
                "pic_name": str(row[i_pic] if i_pic is not None else "").strip()[:255],
                "delivery_remarks": str(row[i_remarks] if i_remarks is not None else "").strip() or None,
                "payment_terms": str(row[i_payment] if i_payment is not None else "").strip() or None,
            }
        )
    wb.close()
    return out


def generate_sql(rows: list[dict], tenant_code: str = "BLUEARM") -> str:
    customers = sorted({r["customer"] for r in rows})
    customer_code = {name: f"S{idx:04d}" for idx, name in enumerate(customers, start=1)}

    lines: list[str] = [
        "-- Sales order list export seed (generated by generate-sales-order-seed-from-export.py)",
        f"-- Rows: {len(rows)} sales orders, {len(customers)} customers",
        f"-- Target tenant: {tenant_code}",
        "-- Idempotent: skips by (tenant_id, sales_order_no).",
        "-- Run after: migrations 013, seed-demo-inventory.sql, seed-demo-quotations.sql",
        "begin;",
        "",
        "do $$",
        "declare",
        "  v_tenant bigint;",
        "  v_user_id bigint;",
        "  v_tax_vat bigint;",
        "  v_currency_id bigint;",
        "  v_loc_hq bigint;",
        "  v_item_id bigint;",
        "  v_soid bigint;",
        "  v_partner_id bigint;",
        "begin",
        f"  select id into v_tenant from public.tenants where company_code = {sql_str(tenant_code)};",
        "  if v_tenant is null then",
        f"    raise warning 'seed-demo-sales-orders-export: tenant {tenant_code} missing — skip';",
        "    return;",
        "  end if;",
        "",
        "  select id into v_user_id from public.users where tenant_id = v_tenant and status = 'active' order by id limit 1;",
        "  select id into v_tax_vat from public.quo_tax_types",
        "  where tenant_id = v_tenant and name = 'Vat Included' and deleted_at is null limit 1;",
        "  select id into v_currency_id from public.quo_currencies",
        "  where tenant_id = v_tenant and is_default = true and deleted_at is null limit 1;",
        "  select id into v_loc_hq from public.inv_locations where tenant_id = v_tenant and location_code = '00001' limit 1;",
        "  select id into v_item_id from public.inv_items where tenant_id = v_tenant and item_code = '00001' limit 1;",
        "",
        "  if v_tax_vat is null or v_currency_id is null or v_loc_hq is null then",
        "    raise warning 'seed-demo-sales-orders-export: missing tax/currency/location — skip';",
        "    return;",
        "  end if;",
        "",
        "  -- Export customers (match existing company_name first)",
    ]

    for name in customers:
        code = customer_code[name]
        lines.append(
            f"  select id into v_partner_id from public.inv_partners"
            f" where tenant_id = v_tenant and company_name = {sql_str(name)} limit 1;"
        )
        lines.append("  if v_partner_id is null then")
        lines.append(
            f"    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status)"
            f" values (v_tenant, {sql_str(code)}, 'customer', {sql_str(name)}, 'active')"
            f" on conflict (tenant_id, partner_code) do nothing;"
        )
        lines.append(
            f"    select id into v_partner_id from public.inv_partners"
            f" where tenant_id = v_tenant and company_name = {sql_str(name)} limit 1;"
        )
        lines.append("  end if;")

    lines.append("")
    lines.append("  -- Sales orders + single summary line each")

    for r in rows:
        delivery_sql = "null" if not r["delivery_date"] else sql_str(str(r["delivery_date"])) + "::date"
        remarks_sql = sql_str(r["delivery_remarks"])
        payment_sql = sql_str(r["payment_terms"])
        lines.append(f"""
  if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = {sql_str(r['sales_order_no'])}) then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = {sql_str(r['customer'])} limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, {sql_str(str(r['order_date']))}::date, {r['date_seq']}, {sql_str(r['sales_order_no'])},
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, {sql_str(r['pic_name'])}, v_loc_hq,
        {delivery_sql}, {remarks_sql}, {payment_sql},
        {sql_str(r['progress_status'])}, {r['subtotal']}, {r['tax_total']}, {r['grand_total']}, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left({sql_str(r['item_summary'])}, 500), {sql_str(r['item_summary'])},
        1, {r['subtotal']}, {r['subtotal']}, {r['tax_total']}, {r['grand_total']}, {r['grand_total']}
      );
    end if;
  end if;""".strip())

    lines.extend(
        [
            "end $$;",
            "",
            "do $$",
            "declare",
            "  v_tenant bigint;",
            "  v_d date;",
            "  v_max_date_seq int;",
            "  v_max_ref_seq int;",
            "begin",
            f"  select id into v_tenant from public.tenants where company_code = {sql_str(tenant_code)};",
            "  if v_tenant is null then return; end if;",
            "  for v_d in",
            "    select distinct order_date from public.so_sales_orders where tenant_id = v_tenant and deleted_at is null",
            "  loop",
            "    select coalesce(max(date_seq), 0) into v_max_date_seq",
            "    from public.so_sales_orders where tenant_id = v_tenant and order_date = v_d and deleted_at is null;",
            "    select coalesce(max(substring(sales_order_no from 7)::int), 0) into v_max_ref_seq",
            "    from public.so_sales_orders",
            "    where tenant_id = v_tenant and order_date = v_d and deleted_at is null",
            "      and sales_order_no ~ ('^' || to_char(v_d, 'YYMMDD') || '[0-9]{3}$');",
            "    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)",
            "    values (v_tenant, 'sales_order_date_seq', v_d, v_max_date_seq)",
            "    on conflict (tenant_id, sequence_key, bucket_date)",
            "    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);",
            "    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)",
            "    values (v_tenant, 'sales_order_no', v_d, v_max_ref_seq)",
            "    on conflict (tenant_id, sequence_key, bucket_date)",
            "    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);",
            "  end loop;",
            "end $$;",
            "",
            "commit;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "xlsx",
        nargs="?",
        default=str(Path(__file__).parent / "fixtures" / "sales-order-list-export.xlsx"),
        help="Path to Sales Order List export .xlsx",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(Path(__file__).parent / "seed-demo-sales-orders-export.sql"),
        help="Output SQL path",
    )
    parser.add_argument("--tenant", default="BLUEARM")
    args = parser.parse_args()

    rows = load_rows(Path(args.xlsx))
    sql = generate_sql(rows, tenant_code=args.tenant)
    out = Path(args.output)
    out.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(rows)} sales orders to {out} ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
