#!/usr/bin/env python3
"""Generate seed-demo-quotations-export.sql from quotation list Excel export."""

from __future__ import annotations

import argparse
import re
from datetime import date, datetime
from pathlib import Path

import openpyxl

TAX_RATE = {
    "Vat Included": 0.12,
    "VAT-Inc 5%": 0.05,
    "Non-VAT": 0.0,
}

TAX_NAME_SQL = {
    "Vat Included": "Vat Included",
    "VAT-Inc 5%": "VAT-Inc 5%",
    "Non-VAT": "Non-VAT",
}


def sql_str(s: str | None) -> str:
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def parse_date_no(raw: str) -> tuple[date, int]:
    raw = str(raw).strip()
    m = re.match(r"^(\d{1,2})/(\d{1,2})/(\d{4})\s*-\s*(\d+)$", raw)
    if not m:
        raise ValueError(f"bad date-no: {raw!r}")
    month, day, year, seq = m.groups()
    return date(int(year), int(month), int(day)), int(seq)


def parse_validity(text: str | None, order: date) -> tuple[str | None, int | None, date | None]:
    if not text:
        return None, None, None
    t = str(text).strip()
    upper = t.upper()
    if upper.endswith("DAYS") or upper.endswith("DAY"):
        m = re.search(r"(\d+)", t)
        days = int(m.group(1)) if m else None
        if days:
            return t, days, order.fromordinal(order.toordinal() + days)
        return t, None, None
    # e.g. JUNE 28 or JUNE 30, 2026
    months = {
        "JANUARY": 1,
        "FEBRUARY": 2,
        "MARCH": 3,
        "APRIL": 4,
        "MAY": 5,
        "JUNE": 6,
        "JULY": 7,
        "AUGUST": 8,
        "SEPTEMBER": 9,
        "OCTOBER": 10,
        "NOVEMBER": 11,
        "DECEMBER": 12,
    }
    m = re.match(r"^([A-Z]+)\s+(\d{1,2})(?:,\s*(\d{4}))?$", upper)
    if m:
        mon_name, day_s, year_s = m.groups()
        mon = months.get(mon_name)
        if mon:
            yr = int(year_s) if year_s else order.year
            try:
                until = date(yr, mon, int(day_s))
                return t, None, until
            except ValueError:
                pass
    return t, None, None


def split_amounts(grand: float, tax_name: str) -> tuple[float, float, float]:
    rate = TAX_RATE.get(tax_name, 0.12)
    if rate <= 0:
        return grand, 0.0, grand
    subtotal = round(grand / (1 + rate), 4)
    tax = round(grand - subtotal, 4)
    return subtotal, tax, grand


def load_rows(xlsx: Path) -> list[dict]:
    wb = openpyxl.load_workbook(xlsx, read_only=True, data_only=True)
    ws = wb["Quotation List"]
    out: list[dict] = []
    for row in ws.iter_rows(min_row=3, values_only=True):
        if not row or not row[2] or row[6] is None:
            continue
        date_no, tax_name, ref_no, customer, item_summary, validity, amount, progress, voucher, _, creator, _ = row[:12]
        customer = str(customer or "").strip()
        if not customer:
            continue
        order_date, date_seq = parse_date_no(str(date_no))
        grand = float(amount)
        subtotal, tax_total, grand_total = split_amounts(grand, str(tax_name))
        val_text, val_days, val_until = parse_validity(validity, order_date)
        out.append(
            {
                "order_date": order_date,
                "date_seq": date_seq,
                "reference_no": str(ref_no).strip(),
                "tax_name": str(tax_name).strip(),
                "customer": customer,
                "item_summary": str(item_summary or "").strip()[:500],
                "validity_text": val_text,
                "validity_days": val_days,
                "valid_until": val_until,
                "subtotal": subtotal,
                "tax_total": tax_total,
                "grand_total": grand_total,
                "progress_status": "in_progress" if str(progress).strip().lower() == "in progress" else "unconfirmed",
                "voucher_status": "completed" if str(voucher).strip().lower() == "confirm" else "none",
                "pic_name": str(creator or "").strip()[:255],
            }
        )
    wb.close()
    return out


def generate_sql(rows: list[dict], tenant_code: str = "BLUEARM") -> str:
    customers = sorted({r["customer"] for r in rows})
    customer_code = {name: f"E{idx:04d}" for idx, name in enumerate(customers, start=1)}

    lines: list[str] = [
        "-- Quotation list export seed (generated by generate-quotation-seed-from-export.py)",
        f"-- Rows: {len(rows)} quotations, {len(customers)} customers",
        f"-- Target tenant: {tenant_code}",
        "-- Idempotent: skips by (tenant_id, reference_no).",
        "-- Run after: migrations 010-011, seed-demo-inventory.sql (location/items).",
        "begin;",
        "",
        "do $$",
        "declare",
        "  v_tenant bigint;",
        "  v_user_id bigint;",
        "  v_currency_id bigint;",
        "  v_loc_hq bigint;",
        "  v_item_id bigint;",
        "  v_qid bigint;",
        "  v_tax_id bigint;",
        "  v_partner_id bigint;",
        "begin",
        f"  select id into v_tenant from public.tenants where company_code = {sql_str(tenant_code)};",
        "  if v_tenant is null then",
        f"    raise warning 'seed-demo-quotations-export: tenant {tenant_code} missing — skip';",
        "    return;",
        "  end if;",
        "",
        "  select id into v_user_id from public.users where tenant_id = v_tenant and status = 'active' order by id limit 1;",
        "  select id into v_currency_id from public.quo_currencies where tenant_id = v_tenant and is_default = true and deleted_at is null limit 1;",
        "  select id into v_loc_hq from public.inv_locations where tenant_id = v_tenant and location_code = '00001' limit 1;",
        "  select id into v_item_id from public.inv_items where tenant_id = v_tenant and item_code = '00001' limit 1;",
        "",
        "  if v_currency_id is null or v_loc_hq is null then",
        "    raise warning 'seed-demo-quotations-export: missing currency/location — skip';",
        "    return;",
        "  end if;",
        "",
        "  -- Export customers",
    ]

    for name in customers:
        code = customer_code[name]
        lines.append(
            f"  insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status)"
            f" values (v_tenant, {sql_str(code)}, 'customer', {sql_str(name)}, 'active')"
            f" on conflict (tenant_id, partner_code) do nothing;"
        )

    lines.append("")
    lines.append("  -- Quotations + single summary line each")

    for r in rows:
        code = customer_code[r["customer"]]
        tax_sql = sql_str(TAX_NAME_SQL.get(r["tax_name"], r["tax_name"]))
        val_until = f"{r['valid_until']!s}" if r["valid_until"] else None
        val_days = str(r["validity_days"]) if r["validity_days"] is not None else "null"
        val_text = sql_str(r["validity_text"])

        lines.append(f"""
  if not exists (select 1 from public.quo_quotations where tenant_id = v_tenant and reference_no = {sql_str(r['reference_no'])})
     and not exists (select 1 from public.quo_quotations where tenant_id = v_tenant and order_date = {sql_str(str(r['order_date']))}::date and date_seq = {r['date_seq']} and deleted_at is null) then
    select id into v_tax_id from public.quo_tax_types where tenant_id = v_tenant and name = {tax_sql} and deleted_at is null limit 1;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and partner_code = {sql_str(code)} limit 1;
    if v_tax_id is not null and v_partner_id is not null then
      insert into public.quo_quotations (
        tenant_id, order_date, date_seq, reference_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        quotation_validity_text, validity_days, valid_until,
        progress_status, voucher_status,
        subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, {sql_str(str(r['order_date']))}::date, {r['date_seq']}, {sql_str(r['reference_no'])},
        v_tax_id, v_currency_id, v_partner_id, v_user_id, {sql_str(r['pic_name'])}, v_loc_hq,
        {val_text}, {val_days}, {'null' if not val_until else sql_str(val_until) + '::date'},
        {sql_str(r['progress_status'])}, {sql_str(r['voucher_status'])},
        {r['subtotal']}, {r['tax_total']}, {r['grand_total']}, v_user_id
      ) returning id into v_qid;

      insert into public.quo_quotation_lines (
        quotation_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_qid, 1, v_item_id, '00001', left({sql_str(r['item_summary'])}, 500), {sql_str(r['item_summary'])},
        1, {r['subtotal']}, {r['subtotal']}, {r['tax_total']}, {r['grand_total']}, {r['grand_total']}
      );
    end if;
  end if;""".strip())

    lines.extend(
        [
            "end $$;",
            "",
            "-- Sync quotation sequence counters for seeded order dates",
            "do $$",
            "declare",
            "  v_tenant bigint;",
            "  v_d date;",
            "  v_max_date_seq int;",
            "  v_max_ref_seq int;",
            "begin",
            f"  select id into v_tenant from public.tenants where company_code = {sql_str(tenant_code)};",
            "  if v_tenant is null then return; end if;",
            "  for v_d in",
            "    select distinct order_date from public.quo_quotations where tenant_id = v_tenant and deleted_at is null",
            "  loop",
            "    select coalesce(max(date_seq), 0) into v_max_date_seq",
            "    from public.quo_quotations where tenant_id = v_tenant and order_date = v_d and deleted_at is null;",
            "    select coalesce(max(substring(reference_no from 7)::int), 0) into v_max_ref_seq",
            "    from public.quo_quotations",
            "    where tenant_id = v_tenant and order_date = v_d and deleted_at is null",
            "      and reference_no ~ ('^' || to_char(v_d, 'YYMMDD') || '[0-9]{3}$');",
            "    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)",
            "    values (v_tenant, 'quotation_date_seq', v_d, v_max_date_seq)",
            "    on conflict (tenant_id, sequence_key, bucket_date)",
            "    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);",
            "    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)",
            "    values (v_tenant, 'quotation_reference_no', v_d, v_max_ref_seq)",
            "    on conflict (tenant_id, sequence_key, bucket_date)",
            "    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);",
            "  end loop;",
            "end $$;",
            "",
            "commit;",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "xlsx",
        nargs="?",
        default=str(Path.home() / "Downloads" / "KCFB6FYPWPSCRQS.xlsx"),
        help="Path to quotation list export .xlsx",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(Path(__file__).parent / "seed-demo-quotations-export.sql"),
        help="Output SQL path",
    )
    parser.add_argument("--tenant", default="BLUEARM")
    args = parser.parse_args()

    rows = load_rows(Path(args.xlsx))
    sql = generate_sql(rows, tenant_code=args.tenant)
    out = Path(args.output)
    out.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(rows)} quotations to {out} ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
