#!/usr/bin/env python3
"""Generate seed-demo-items-export.sql from Item List Excel export."""

from __future__ import annotations

import argparse
from pathlib import Path

import openpyxl

from export_seed_common import (
    col_index,
    find_sheet,
    header_row_index,
    normalize_item_code,
    parse_money,
    sql_str,
)


def load_rows(xlsx: Path) -> list[dict]:
    wb = openpyxl.load_workbook(xlsx, read_only=True, data_only=True)
    sheet = find_sheet(wb, ["Item List", "Items", "Item"], "Item Code")
    ws = wb[sheet]
    hdr_idx = header_row_index(ws, ("Item Code", "Item Name"))
    headers = next(ws.iter_rows(min_row=hdr_idx, max_row=hdr_idx, values_only=True))
    i_code = col_index(headers, "Item Code")
    i_name = col_index(headers, "Item Name")
    i_purchase = col_index(headers, "Purchase Price", "Purchase")
    i_sale = col_index(headers, "Sale Price", "Sales Price")
    i_vip = col_index(headers, "VIP Price", "Vip Price")
    i_active = col_index(headers, "Active", "Status")
    if i_code is None or i_name is None:
        raise ValueError(f"missing required columns in headers: {headers}")

    seen: set[str] = set()
    out: list[dict] = []
    for row in ws.iter_rows(min_row=hdr_idx + 1, values_only=True):
        if not row or row[i_code] in (None, ""):
            continue
        raw_code = str(row[i_code]).strip()
        name = str(row[i_name] or "").strip()
        if not name:
            continue
        purchase = parse_money(row[i_purchase] if i_purchase is not None else None)
        sale = parse_money(row[i_sale] if i_sale is not None else None)
        vip = parse_money(row[i_vip] if i_vip is not None else None)
        active_raw = str(row[i_active] if i_active is not None else "YES").strip().upper()
        status = "active" if active_raw in ("YES", "Y", "ACTIVE", "1", "TRUE") else "inactive"
        code = normalize_item_code(raw_code, seen)
        out.append(
            {
                "item_code": code,
                "export_code": raw_code,
                "item_name": name[:500],
                "purchase_price": purchase if purchase is not None else 0.0,
                "sales_price": sale if sale is not None else 0.0,
                "vip_price": vip if vip is not None else 0.0,
                "status": status,
            }
        )
    wb.close()
    return out


def generate_sql(rows: list[dict], tenant_code: str = "BLUEARM") -> str:
    lines: list[str] = [
        "-- Item list export seed (generated by generate-item-seed-from-export.py)",
        f"-- Rows: {len(rows)} items",
        f"-- Target tenant: {tenant_code}",
        "-- Idempotent: upserts by (tenant_id, item_code).",
        "-- Run after: seed-demo-inventory.sql",
        "-- Note: legacy codes longer than 5 chars are mapped to char(5) (last 5 chars).",
        "begin;",
        "",
        "do $$",
        "declare",
        "  v_tenant bigint;",
        "  v_max_item int;",
        "begin",
        f"  select id into v_tenant from public.tenants where company_code = {sql_str(tenant_code)};",
        "  if v_tenant is null then",
        f"    raise warning 'seed-demo-items-export: tenant {tenant_code} missing — skip';",
        "    return;",
        "  end if;",
        "",
        "  -- Export items",
    ]

    for r in rows:
        lines.append(
            "  insert into public.inv_items (tenant_id, item_code, item_name, purchase_price, sales_price, vip_price, status)"
            f" values (v_tenant, {sql_str(r['item_code'])}, {sql_str(r['item_name'])},"
            f" {r['purchase_price']}, {r['sales_price']}, {r['vip_price']}, {sql_str(r['status'])})"
            " on conflict (tenant_id, item_code) do update set"
            " item_name = excluded.item_name,"
            " purchase_price = excluded.purchase_price,"
            " sales_price = excluded.sales_price,"
            " vip_price = excluded.vip_price,"
            " status = excluded.status,"
            " updated_at = now();"
        )

    lines.extend(
        [
            "",
            "  select coalesce(max(substring(item_code from '^[0-9]+$')::int), 0) into v_max_item",
            "  from public.inv_items where tenant_id = v_tenant and item_code ~ '^[0-9]{5}$';",
            "",
            "  insert into public.tenant_code_sequences (tenant_id, entity_type, last_value)",
            "  values (v_tenant, 'item', greatest(v_max_item, 150))",
            "  on conflict (tenant_id, entity_type)",
            "  do update set last_value = greatest(tenant_code_sequences.last_value, excluded.last_value);",
            "end $$;",
            "",
            "commit;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "xlsx",
        nargs="?",
        default=str(Path(__file__).parent / "fixtures" / "item-list-export.xlsx"),
        help="Path to Item List export .xlsx",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(Path(__file__).parent / "seed-demo-items-export.sql"),
        help="Output SQL path",
    )
    parser.add_argument("--tenant", default="BLUEARM")
    args = parser.parse_args()

    rows = load_rows(Path(args.xlsx))
    sql = generate_sql(rows, tenant_code=args.tenant)
    out = Path(args.output)
    out.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(rows)} items to {out} ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
