-- Sales order list export seed (generated by generate-sales-order-seed-from-export.py)
-- Rows: 11 sales orders, 9 customers
-- Target tenant: BLUEARM
-- Idempotent: skips by (tenant_id, sales_order_no).
-- Run after: migrations 013, seed-demo-inventory.sql, seed-demo-quotations.sql
begin;

do $$
declare
  v_tenant bigint;
  v_user_id bigint;
  v_tax_vat bigint;
  v_currency_id bigint;
  v_loc_hq bigint;
  v_item_id bigint;
  v_soid bigint;
  v_partner_id bigint;
begin
  select id into v_tenant from public.tenants where company_code = 'BLUEARM';
  if v_tenant is null then
    raise warning 'seed-demo-sales-orders-export: tenant BLUEARM missing — skip';
    return;
  end if;

  select id into v_user_id from public.users where tenant_id = v_tenant and status = 'active' order by id limit 1;
  select id into v_tax_vat from public.quo_tax_types
  where tenant_id = v_tenant and name = 'Vat Included' and deleted_at is null limit 1;
  select id into v_currency_id from public.quo_currencies
  where tenant_id = v_tenant and is_default = true and deleted_at is null limit 1;
  select id into v_loc_hq from public.inv_locations where tenant_id = v_tenant and location_code = '00001' limit 1;
  select id into v_item_id from public.inv_items where tenant_id = v_tenant and item_code = '00001' limit 1;

  if v_tax_vat is null or v_currency_id is null or v_loc_hq is null then
    raise warning 'seed-demo-sales-orders-export: missing tax/currency/location — skip';
    return;
  end if;

  -- Export customers (match existing company_name first)
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'Clinica Prime' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0001', 'customer', 'Clinica Prime', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'Clinica Prime' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'GOLDEN GREAT PEAK ENGLISH SCHOOL INC.' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0002', 'customer', 'GOLDEN GREAT PEAK ENGLISH SCHOOL INC.', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'GOLDEN GREAT PEAK ENGLISH SCHOOL INC.' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'INSUPHIL INDUSTRIAL CORP.' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0003', 'customer', 'INSUPHIL INDUSTRIAL CORP.', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'INSUPHIL INDUSTRIAL CORP.' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'JUANEL CASAVERDE' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0004', 'customer', 'JUANEL CASAVERDE', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'JUANEL CASAVERDE' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'KONSTRAPHILS.INC.' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0005', 'customer', 'KONSTRAPHILS.INC.', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'KONSTRAPHILS.INC.' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'MIGRATION UNITY' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0006', 'customer', 'MIGRATION UNITY', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'MIGRATION UNITY' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'RESPONSIVCODE TECHNOLOGY SOLUTIONS' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0007', 'customer', 'RESPONSIVCODE TECHNOLOGY SOLUTIONS', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'RESPONSIVCODE TECHNOLOGY SOLUTIONS' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'SPC ISLAND POWER CORPORATION' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0008', 'customer', 'SPC ISLAND POWER CORPORATION', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'SPC ISLAND POWER CORPORATION' limit 1;
  end if;
  select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'ZAFIRE DISTRIBUTORS INC.' limit 1;
  if v_partner_id is null then
    insert into public.inv_partners (tenant_id, partner_code, partner_kind, company_name, status) values (v_tenant, 'S0009', 'customer', 'ZAFIRE DISTRIBUTORS INC.', 'active') on conflict (tenant_id, partner_code) do nothing;
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'ZAFIRE DISTRIBUTORS INC.' limit 1;
  end if;

  -- Sales orders + single summary line each
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260626004') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'Clinica Prime' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-26'::date, 4, '260626004',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Mjan Saceda', v_loc_hq,
        '2026-06-26'::date, 'DELIVERY DATE : JUNE 29 (MORNING or AFTERNOON)', 'CASH',
        'in_progress', 133.9286, 16.0714, 150.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('MANHATTAN USB OPTICAL WIRED MOUSE (BLACK) [Peripherals]', 500), 'MANHATTAN USB OPTICAL WIRED MOUSE (BLACK) [Peripherals]',
        1, 133.9286, 133.9286, 16.0714, 150.0, 150.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260626003') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'SPC ISLAND POWER CORPORATION' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-26'::date, 3, '260626003',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Chrisa Barte', v_loc_hq,
        '2026-06-27'::date, 'None', 'BANK TRANSFER',
        'in_progress', 758.9286, 91.0714, 850.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('GEILTIMA 8GB 3200 DDR4 WITH HEATSINK LONGDIM [RAM]', 500), 'GEILTIMA 8GB 3200 DDR4 WITH HEATSINK LONGDIM [RAM]',
        1, 758.9286, 758.9286, 91.0714, 850.0, 850.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260626002') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'MIGRATION UNITY' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-26'::date, 2, '260626002',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Jenabie Tahanlangit', v_loc_hq,
        '2026-06-26'::date, 'PLEASE DELIVER THIS AFTERNOON 6-26-2026 FOR THE DELIVERY: LOOK FOR MAAM SHEILD NUMBER: +639190094830', 'BANK TRANSFER',
        'in_progress', 49553.5714, 5946.4286, 55500.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('LENOVO IDEAPAD SLIM 3 14IRH10-83K000ERPH I7-13620H/8GB+8GB/512GB NVME/14/W11H/OFFC21HS+365BASIC (GRY) [Laptop] and 2 more', 500), 'LENOVO IDEAPAD SLIM 3 14IRH10-83K000ERPH I7-13620H/8GB+8GB/512GB NVME/14/W11H/OFFC21HS+365BASIC (GRY) [Laptop] and 2 more',
        1, 49553.5714, 49553.5714, 5946.4286, 55500.0, 55500.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260626001') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'JUANEL CASAVERDE' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-26'::date, 1, '260626001',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Mariano Villordon Jr', v_loc_hq,
        '2026-06-28'::date, 'None', '20 DAYS',
        'in_progress', 5446.4286, 653.5714, 6100.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('GAMDIAS ATLAS HD27H III VA 200Hz FHD MONITOR [Monitors]', 500), 'GAMDIAS ATLAS HD27H III VA 200Hz FHD MONITOR [Monitors]',
        1, 5446.4286, 5446.4286, 653.5714, 6100.0, 6100.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260625002') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'GOLDEN GREAT PEAK ENGLISH SCHOOL INC.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-25'::date, 2, '260625002',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Katherine Borinaga', v_loc_hq,
        '2026-06-25'::date, 'None', '30 DAYS TERMS',
        'in_progress', 2991.0714, 358.9286, 3350.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('EPOS IMPACT 860T ANC USB WIRED HEADSET [Headset/Speaker]', 500), 'EPOS IMPACT 860T ANC USB WIRED HEADSET [Headset/Speaker]',
        1, 2991.0714, 2991.0714, 358.9286, 3350.0, 3350.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260625001') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'ZAFIRE DISTRIBUTORS INC.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-25'::date, 1, '260625001',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Katherine Borinaga', v_loc_hq,
        '2026-06-25'::date, 'WAITING FOR THEIR CHEQUE(OVERDUE)', '30 DAYS',
        'in_progress', 63705.3571, 7644.6429, 71350.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('ACER ASPIRE TC1785 I5-14400/8GB/1TB+256GB/W11H/OFC21HS+365BASIC DESKTOP (DT.BLNSP.003) [All In One PC]', 500), 'ACER ASPIRE TC1785 I5-14400/8GB/1TB+256GB/W11H/OFC21HS+365BASIC DESKTOP (DT.BLNSP.003) [All In One PC]',
        1, 63705.3571, 63705.3571, 7644.6429, 71350.0, 71350.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260624003') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'ZAFIRE DISTRIBUTORS INC.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-24'::date, 3, '260624003',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Katherine Borinaga', v_loc_hq,
        '2026-06-24'::date, 'None', '30 DAYS',
        'in_progress', 1071.4286, 128.5714, 1200.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('VENTION HDMI TO VGA CONVERTER ADAPTER W/ AUDIO (AIDB0) [Peripherals] and 1 more', 500), 'VENTION HDMI TO VGA CONVERTER ADAPTER W/ AUDIO (AIDB0) [Peripherals] and 1 more',
        1, 1071.4286, 1071.4286, 128.5714, 1200.0, 1200.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260624002') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'RESPONSIVCODE TECHNOLOGY SOLUTIONS' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-24'::date, 2, '260624002',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Mariano Villordon Jr', v_loc_hq,
        '2026-06-24'::date, 'ako lang deliver ani thanks 6/24/26 SI 0034 DR 0048', 'gcash',
        'completed', 6607.1429, 792.8571, 7400.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('SEAGATE SKYHAWK 2TB HDD [Storage]', 500), 'SEAGATE SKYHAWK 2TB HDD [Storage]',
        1, 6607.1429, 6607.1429, 792.8571, 7400.0, 7400.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260624001') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'KONSTRAPHILS.INC.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-24'::date, 1, '260624001',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Nel Tristan Juarez', v_loc_hq,
        '2026-06-24'::date, 'None', 'FREEBIES SA NO. 3042',
        'in_progress', 1026.7857, 123.2143, 1150.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('HP 932XL Officejet Ink Cartridge - BLACK [Peripherals]', 500), 'HP 932XL Officejet Ink Cartridge - BLACK [Peripherals]',
        1, 1026.7857, 1026.7857, 123.2143, 1150.0, 1150.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260623002') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'INSUPHIL INDUSTRIAL CORP.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-23'::date, 2, '260623002',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Michelle Manlalic', v_loc_hq,
        '2026-06-23'::date, 'None', 'CASH',
        'completed', 160.7143, 19.2857, 180.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('A4TECH OP-330 OPTICAL WHEEL MOUSE USB/BLACK [Mouse]', 500), 'A4TECH OP-330 OPTICAL WHEEL MOUSE USB/BLACK [Mouse]',
        1, 160.7143, 160.7143, 19.2857, 180.0, 180.0
      );
    end if;
  end if;
if not exists (select 1 from public.so_sales_orders where tenant_id = v_tenant and sales_order_no = '260623001') then
    select id into v_partner_id from public.inv_partners where tenant_id = v_tenant and company_name = 'INSUPHIL INDUSTRIAL CORP.' limit 1;
    if v_partner_id is not null then
      insert into public.so_sales_orders (
        tenant_id, order_date, date_seq, sales_order_no,
        tax_type_id, currency_id, partner_id, pic_user_id, pic_name, location_id,
        delivery_date, delivery_remarks, payment_terms,
        progress_status, subtotal, tax_total, grand_total, created_by_user_id
      ) values (
        v_tenant, '2026-06-23'::date, 1, '260623001',
        v_tax_vat, v_currency_id, v_partner_id, v_user_id, 'Michelle Manlalic', v_loc_hq,
        '2026-06-23'::date, 'None', 'BANK TRANSFER',
        'in_progress', 1339.2857, 160.7143, 1500.0, v_user_id
      ) returning id into v_soid;

      insert into public.so_sales_order_lines (
        sales_order_id, line_no, item_id, item_code, item_name, description,
        qty, unit_non_vat, non_vat_total, tax_amount, unit_vat_inc, line_total
      ) values (
        v_soid, 1, v_item_id, '00001', left('INHOUSE: Diagnose and Repair Laptop/Computer Plus parts/materials used [Services]', 500), 'INHOUSE: Diagnose and Repair Laptop/Computer Plus parts/materials used [Services]',
        1, 1339.2857, 1339.2857, 160.7143, 1500.0, 1500.0
      );
    end if;
  end if;
end $$;

do $$
declare
  v_tenant bigint;
  v_d date;
  v_max_date_seq int;
  v_max_ref_seq int;
begin
  select id into v_tenant from public.tenants where company_code = 'BLUEARM';
  if v_tenant is null then return; end if;
  for v_d in
    select distinct order_date from public.so_sales_orders where tenant_id = v_tenant and deleted_at is null
  loop
    select coalesce(max(date_seq), 0) into v_max_date_seq
    from public.so_sales_orders where tenant_id = v_tenant and order_date = v_d and deleted_at is null;
    select coalesce(max(substring(sales_order_no from 7)::int), 0) into v_max_ref_seq
    from public.so_sales_orders
    where tenant_id = v_tenant and order_date = v_d and deleted_at is null
      and sales_order_no ~ ('^' || to_char(v_d, 'YYMMDD') || '[0-9]{3}$');
    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)
    values (v_tenant, 'sales_order_date_seq', v_d, v_max_date_seq)
    on conflict (tenant_id, sequence_key, bucket_date)
    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);
    insert into public.tenant_daily_sequences (tenant_id, sequence_key, bucket_date, last_value)
    values (v_tenant, 'sales_order_no', v_d, v_max_ref_seq)
    on conflict (tenant_id, sequence_key, bucket_date)
    do update set last_value = greatest(tenant_daily_sequences.last_value, excluded.last_value);
  end loop;
end $$;

commit;
